apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::557056613444:user/sharon-admin
      username: sharon-admin
      groups:
        - system:masters